= {lab_name}

In the ever-evolving landscape of information technology (IT), containers have emerged as a fundamental component that revolutionizes software development, deployment, and management. These lightweight and portable units encapsulate applications, their dependencies, and even the underlying operating system. However, as containers have become pervasive in IT, operating system customization remains a persistent challenge, both in the context of day two configuration management and during the initial creation of operating system (OS) images.

In this lab you will learn how to evolve your containers into full fledged operating systems.

=== Lab Access

In the Instruqt browser there will be 4 tabs available during this lab.

The `Terminal` tab is the main host and hypervisor for this lab. Unless instructed, most of the exercises will be done here
The `Code editor` tab is provided as a convinience to help with editing files as an alternative to vim or nano
The SSH tabs will each be used to access the VM named in the tab title. Until those VMs are launched these will show an error.
To connect to the VM once it's been launched, hit the refresh button in the top right corner of the title bar.