TIP: This workshop uses blocks which contain runnable commands and represent output. The blocks marked with `bash`, `dockerfile`, etc 
in the upper right corner can be copied and pasted into a terminal window instead of being typed. This is provided as a convenience.

= System setup
In this lab, you will be cloning the lab helper scripts and preparing
the host, as well as setting up the required access for Red Hat resources.

[#login]
== Red Hat registry login

This lab has already logged into the Red Hat terms based registry, however if there is an issue a convinience command has been created.
To log back into the registry at any time you can use:"

[source,console]
----
reglogin
----


[#high-level]
== Preparing the host for container building

In this final part of the setup, you will:

  * download some additional files
  * finalize the system config

There is a script to do it all for you:

[source,console]
----
make setup
----

[#status]
== Checking the setup

One final check before you advance to the next lab. All exercises will be listed in this browser window, there is no additional challenge in the Instruqt UI.

[source,console]
----
make status
----

The output from the command above should be similar to the following:

....
git status
On branch rh1-lab
Your branch is up to date with 'origin/rh1-lab'.

nothing to commit, working tree clean
podman login --get-login registry.redhat.io
1979710|rhel-tmm
podman image exists "registry.redhat.io/rhel9/rhel-bootc:9.4"
podman image exists "registry.redhat.io/rhel9/bootc-image-builder:latest"
     Active: inactive (dead)
 Id   Name   State
--------------------

net.ipv4.ip_unprivileged_port_start = 80
ID            NAME        CPU %       MEM USAGE / LIMIT  MEM %       NET IO          BLOCK IO    PIDS        CPU TIME    AVG CPU %
dba45d693db0  registry    0.01%       13.03MB / 8.056GB  0.16%       2.774kB / 908B  0B / 0B     5           28.016ms    0.01%
Starting Containerfile available
....
