= Exploring alternate user creation methods

In this exercise, you'll explore other ways to create users and add credentials to image mode hosts.

[#add-creds]
== Embedding emergency credentials into an image
In the previous exercises, we've created users and added ssh keys at install time, either via a blueprint file 
passed to `bootc-image-builder` or via kickstart to Anaconda. There are many ways and many reasons why handling 
users would happen at any particular stage of the process, during deployment or after install via network authentication.

In addition to adding users during the creation of a host system, via `bootc-image-builder`, `cloud-init`, or some other means, we can also create users during
the creation of the bootc image. This can be useful in certain cases where particular emergency users are needed in environments with limited connectivity. 
These users and credentials would be tied to the image, which means controlling how secrets are used in the build are important to understand before going 
down this path. You will want to explore more before making this choice in your own environment.

[#secrets]
== Using podman secrets at build time

We will use an addtional feature of `podman` to get the credentials we want to embed passed to the image safely.

You can now edit the `Containerfile` using the `Code editor` to match the following:

NOTE: Be sure you've selected the `/root/rh-summit-2024-lb1506/Containerfile` in the file picker

[source,dockerfile]
----
FROM registry.redhat.io/rhel9/rhel-bootc:9.4

COPY templates/30-auth-system.conf /etc/ssh/sshd_config.d/30-auth-system.conf # <1>
RUN mkdir -p /usr/ssh # <2>
RUN --mount=type=secret,id=SSHPUBKEY cat /run/secrets/SSHPUBKEY > /usr/ssh/root.keys && chmod 0600 /usr/ssh/root.keys # <3>

ADD etc/ /etc

RUN dnf install -y httpd

RUN <<EOF
    mv /var/www /usr/share/www
    sed -i 's-/var/www-/usr/share/www-' /etc/httpd/conf/httpd.conf
EOF

RUN echo "Hello Red Hat One 2025!!" > /usr/share/www/html/index.html

RUN systemctl enable httpd.service
----
<1> `COPY templates...` -> adds a drop in for sshd to look for public keys in users global `.keys` file, note this is in `/usr` and tied to the image
<2> `RUN mkdir -p /usr/ssh` -> create the new keys directory in `/usr`
<3> `RUN --mount=type=secret,id=SSHPUBKEY cat /run/secrets/SSHPUBKEY .. ` -> mounts the secret passed via build to a file only available at build time, then copies the contents

You can now build the new container image with the following command, note the `--secret` argument. This is the connection to the `RUN` directive in the Containerfile. At build time, `podman` will take the file passed as `src` and create a temporary secret which we can mount only during the build process. 

The `id` of the secret is also the filename mounted under `/run/secrets`, which we then can extract the contents for our ssh key.

We're also going to use a new tag for this image, like we did in the previous `bootc switch` exercise.

[source,bash]
----
podman build --secret id=SSHPUBKEY,src=/root/.ssh/id_rsa.pub --file Containerfile --tag $REGISTRY/bootc-auth
----

And make sure to push it to the registry:

[source,bash]
----
podman push $REGISTRY/bootc-auth
----

[#switch-creds]
== Changing the virtual machine image

In the `Terminal` tab, you will need to have the full image name for the following commands in the VM ssh session.

[source,bash]
----
podman images | grep auth
----

[NOTE]
====
The QCOW virtual machine you have been working with during this workshop should still be running. You can check this with

[source,bash]
----
virsh --connect qemu:///system list
----

And the output should contain a virtual machine called `qcow`.
====

Switch to the `SSH QCOW VM` tab to change the image the host is tracking.

We can change to our new image with the embedded `root` credentials, substitute the image from the `Terminal` for `your-reg-name/bootc-auth` here.

[source,bash]
----
sudo bootc switch your-reg-name/bootc-auth
----

The output should look something like this:

----
layers already present: 68; layers needed: 7 (126.7 MB)
 452 B [████████████████████] (0s) Fetched layer sha256:2691e6642975            
Pruned images: 0 (layers: 0, objsize: 58.9 MB)
Queued for next boot: $REGISTRY/bootc-auth
  Version: 9.20240721.0
  Digest: sha256:2afd495b9dd3e72aa4926deb1e738af54e0b1bb935803bc6c107bdd919347167
----
As usual, after the command is done you need to reboot the virtual machine
for the changes to take effect. Before doing that, please make sure you are logged in to the
virtual machine and not the hypervisor (the prompt should look like `[lab-user@qcow-vm ~]#`):

TIP: Try searching the bash history for 'reboot' instead of copying from below. Even though we've rolled back the OS, we still have local user state available.

[source,bash]
----
sudo systemctl reboot
----

[#user-test]
== Testing the changes

From the `Terminal` tab you can test the newly added root credentials.

[source,bash]
----
ssh root@qcow
----

And check once again the status of bootc (no need to use `sudo`, you are root):

[source,bash]
----
bootc status
----

The output should look like this:

[source,yaml]
----
apiVersion: org.containers.bootc/v1alpha1
kind: BootcHost
metadata:
  name: host
spec:
  image:
    image: $REGISTRY/bootc-auth
    transport: registry
  bootOrder: default
status:
  staged: null
  booted:
    image:
      image:
        image: $REGISTRY/bootc-auth
        transport: registry
      version: 9.20240721.0
      timestamp: null
      imageDigest: sha256:2afd495b9dd3e72aa4926deb1e738af54e0b1bb935803bc6c107bdd919347167
    cachedUpdate: null
    incompatible: false
    pinned: false
    ostree:
      checksum: 6307d9fdc8be3f0c202ce49e311b1d046d6d606dea7bcff51ad5d8910f7887b3
      deploySerial: 0
  rollback:
    image:
      image:
        image: $REGISTRY/bootc-wp
        transport: registry
      version: 9.20240721.0
      timestamp: null
      imageDigest: sha256:af3c6bd4ae7beb9bb10f9846c7bc9d9ba1ede259b4b45e581ddcd97ab2df4380
    cachedUpdate: null
    incompatible: false
    pinned: false
    ostree:
      checksum: 543f6c9a5b8e2f354db71adda5db7ca74b53bcb9fdf8c8fcd391e7c66c77062a
      deploySerial: 0
  rollbackQueued: false
  type: bootcHost
----

Feel free to explore the virtual machine before moving on to the next section, remembering you are now `root`.

Since we've moved away from the WordPress image back to a standard httpd service, you can look for the original 
index file on disk or via `curl`.

Before proceeding, make sure you have logged out of the virtual machine:

[source,bash]
----
logout
----

