TIP: This workshop uses blocks which contain runnable commands and represent output. The blocks marked with `bash`, `dockerfile`, etc 
in the upper right corner can be copied and pasted into a terminal window instead of being typed. This is provided as a convenience.

= System setup
In this lab, you will be cloning the lab helper scripts and preparing
the host, as well as setting up the required access for Red Hat resources.

[#repo]
== Installing Repositories

First, let's start by changing our working directory:

[source,bash]
----
cd rh-summit-2024-lb1506
----

[#login]
== Red Hat registry login

This lab has already logged into the Red Hat terms based registry, however if there is an issue a convinience command has been created.
To log back into the registry at any time you can use:"

[source,bash]
----
reglogin
----


[#high-level]
== Preparing the host for container building

In this final part of the setup, you will:

  * download some additional files
  * finalize the system config

There is a script to do it all for you:

[source,bash]
----
make setup
----

[#status]
== Checking the setup

One final check before you advance to the next lab. All exercises will be listed in this browser window, there is no additional challenge in the Instruqt UI.

[source,bash]
----
make status
----

The output from the command above should be similar to the following:

....
git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
podman login --get-login registry.redhat.io
cgament@redhat.com
podman image exists "registry.redhat.io/rhel9/rhel-bootc:9.4"
podman image exists "quay.io/centos-bootc/bootc-image-builder:latest"
     Active: active (running) since Wed 2024-05-01 17:13:37 EDT; 55s ago
 Id   Name   State
--------------------

net.ipv4.ip_unprivileged_port_start = 80
ID            NAME             CPU %       MEM USAGE / LIMIT  MEM %       NET IO            BLOCK IO    PIDS        CPU TIME    AVG CPU %
fa77d569b19f  summit-registry  0.05%       17.9MB / 67.3GB    0.03%       3.88kB / 1.888kB  0B / 0B     20          18.923277s  0.05%
....
