= Build a bootc container image
In this step you will transform an application container to a bootc image.

[#write]
== Modify the Containerfile

NOTE: The `vim` editor is also available if you don't wish to use the `Code editor`. Users of `vim` should already know the basics
of opening, saving and exiting the editor. 

Let's start with a typical application container and convert it to an image mode host. We'll start
with something simple, a basic webserver running on the Red Hat Universal Base Image. 

Open the `Code editor` tab and select the `Containerfile` in the starting directory.

[source,dockerfile]
----
FROM registry.access.redhat.com/ubi9/ubi

RUN dnf install -y httpd
RUN echo "Hello Red Hat" > /var/www/html/index.html

ENTRYPOINT /usr/sbin/httpd -DFOREGROUND
----

A brief explanation of the key directives in the Containerfile above:

  * `FROM` -> the base container image
  * `ENTRYPOINT` -> the command that will be executed by default at run time

You can now replace the contents as follows:

[source,dockerfile]
----
FROM registry.redhat.io/rhel9/rhel-bootc:9.4

RUN dnf install -y httpd
RUN echo "Hello Red Hat" > /var/www/html/index.html

RUN systemctl enable httpd.service
----

TIP: The editor should auto-save but you can use typical Cmd-S / Ctrl-S keys to manually save changes.

Let's talk about the effects of these changes:

  * The `FROM` field is now pointing to the Red Hat Enterprise Linux 9.4 bootc image instead of the UBI base image.
  This new bootc image is a complete version of RHEL 9.4, much like the KVM image available on the Customer Portal. This 
  image includes all of the OS components to run as a host as well as the new `bootc` commands. It is built using `ostree`
  to facilitate the transactional updates that marks an image mode deployment from a package mode host.
  
  * `RUN systemctl enable httpd.service` replaces the `ENTRYPOINT`.  
  To start the `httpd` service at host startup as you use `systemctl` would with any other host. There's no 
  need to specify an executable that should be run when the container is started by a container engine like 
  podman. 


[#build]
== Build the first bootc image

Return to the `Terminal` tab to build the images.

NOTE: as the registry hostnames in the lab are dynamic, an environment variable will be used instead of a hostname for the registry in all examples. 

As with application containers, you can build this container with standard tools:

  * `--file Containerfile` -> what Containerfile to use for the build
  * `--tag $REGISTRY:bootc` -> the "tag" or name of the resulting container in the format
     <registry>/<repository>:<tag>


[source,bash]
----
podman build --file Containerfile --tag $REGISTRY/bootc
----

If the above command is succesful, the last two lines of the output should read like this:

....
Successfully tagged $REGISTRY/bootc
f1bea10eb37acf2e78a9b01c6242110c1901adbaf40dbce479241c6c735c58da
....

[#distribute]
== Distributing the bootc image

Now that we have a full operating system in a standard OCI container image, we can use
standard container registries to host and distribute our OS images. The only atypical thing so far 
is what's in the base image. How we added software or files to the image is the same as any other 
application container. The special sauce of `bootc` comes when installing or updating a host.

We have a registry available within the lab environment we can push our image to:

[source,bash]
----
podman push $REGISTRY/bootc
----

That's all there is to designing and building a complete operating system. Start with a base, then add software and 
related configurations. You not only have the record of that work you can put under source control in the form of the 
Containerfile, you also have the binary image stored and versioned in the registry.

You've built your first bootc image, and it's now published for use. How do we get from here to a running system?
